apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traq-frontend

spec:
  entryPoints:
    - websecure
  tls:
    secretName: traq-tls
  routes:
    - kind: Rule
      match: Host(`q.trap.jp`)
      priority: -100
      services:
        - namespace: traq-server
          kind: Service
          name: traq-frontend
          port: 8000
          scheme: http
          weight: 1
