apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-mcp

spec:
  template:
    spec:
      containers:
        - name: grafana-mcp
          env:
            - name: GRAFANA_URL
              value: http://grafana.sakura-monitor.svc.cluster.local:3000
