resources:
  - ../../monitor/grafana-mcp

patches:
  - path: ingress-route-patch.yaml
    target:
      kind: IngressRoute
      name: grafana-mcp
  - path: certificate-patch.yaml
    target:
      kind: Certificate
      name: grafana-mcp

generators:
  - ./ksops.yaml
