apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea
spec:
  entryPoints:
    - websecure
  tls:
    secretName: gitea-tls
  routes:
    - kind: Rule
      match: Host(`git-dev.trapti.tech`)
      services:
        - name: gitea
          port: 3000
    - kind: Rule
      match: Host(`git-dev.trapti.tech`)
      services:
        - name: gitea
          port: 2222
