apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-mcp

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: grafana-mcp
  template:
    metadata:
      labels:
        app: grafana-mcp
    spec:
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      containers:
        - name: grafana-mcp
          image: grafana/mcp-grafana:latest
          imagePullPolicy: IfNotPresent
          args:
            - --transport
            - sse
            - --disable-write
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: GRAFANA_URL
              value: http://grafana.monitor.svc.cluster.local:3000
            - name: GRAFANA_SERVICE_ACCOUNT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: grafana-mcp-token
                  key: token

          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
