apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-mcp

spec:
  entryPoints:
    - websecure
  tls:
    secretName: grafana-mcp-tls
  routes:
    - kind: Rule
      match: Host(`grafana-mcp.trap.jp`)
      middlewares:
        - name: grafana-mcp-basic-auth
          namespace: monitor
      services:
        - namespace: monitor
          kind: Service
          name: grafana-mcp
          port: http
          scheme: http
          weight: 1
