apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitor

resources:
  - certificate.yaml
  - deployment.yaml
  - ingress-route.yaml
  - middleware.yaml
  - service.yaml

generators:
  - ksops.yaml

configurations:
  - kustomize-config.yaml
