domain: ""
clientID: ""

secretName: "common-secret"
oauthSecretName: ""

cookieName: "_forward_auth"
headers:
  - name: X-Forwarded-User
    source: name
  - name: X-Showcase-User
    source: name

image:
  name: "ghcr.io/traptitech/traefik-forward-auth"
  # renovate:image-tag imageName=ghcr.io/traptitech/traefik-forward-auth
  tag: "3.3.2"
