apiVersion: apps/v1
kind: Deployment
metadata:
  name: jomon-frontend
  labels:
    app.kubernetes.io/name: jomon-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jomon-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jomon-frontend
    spec:
      containers:
        - name: jomon-frontend
          image: ghcr.io/traptitech/jomon-ui:main@sha256:16171abfbd686645ca02b936c219c520fb814d8d36cecdf191894f8f1fd6228a
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
