apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jomon
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jomon-dev.trapti.tech`) && PathPrefix(`/api`)
      priority: -99
      kind: Rule
      services:
        - name: jomon
          port: 80
    - match: Host(`jomon-dev.trapti.tech`)
      priority: -100
      kind: Rule
      services:
        - name: jomon-frontend
          port: 80
  tls:
    secretName: jomon-dev-tls
