apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jomon-ingressroute
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jomon-dev.trapti.tech`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: jomon-backend
          port: 80
    - match: Host(`jomon-dev.trapti.tech`)
      kind: Rule
      services:
        - name: jomon-frontend
          port: 80
