resources:
  - ../jomon
  - frontend-service.yaml
  - frontend-deployment.yaml

patches:
  - path: backend-deployment-patch.yaml
    target:
      kind: Deployment
      name: jomon
  - path: ingress-route-patch.yaml
    target:
      kind: IngressRoute
      name: jomon

generators:
  - ./ksops.yaml
