resources:
  - ../jomon

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: jomon
  - path: ingress-route-patch.yaml
    target:
      kind: IngressRoute
      name: jomon
  - path: certificate-patch.yaml
    target:
      kind: Certificate
      name: jomon-certificate

generators:
  - ./ksops.yaml
