apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preview-traq
  namespace: argocd

# https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Pull-Request/
spec:
  generators:
    - pullRequest:
        github:
          owner: traPtitech
          repo: traQ_S-UI
          tokenRef:
            secretName: preview-pr-generator
            key: token
          # Labels is used to filter the PRs that you want to target. (optional)
          # labels:
          #   - preview
        requeueAfterSeconds: 1800
  template:
    metadata:
      name: "preview-traq-{{number}}"
      labels:
        pr-preview: "true"
        pr-preview-type: "traq"
        skip-default-notification: "true"
      annotations:
        notifications.argoproj.io/subscribe.on-preview-deployed.traq-preview: ""
        pr-preview-head-sha: "{{head_sha}}"
    spec:
      source:
        repoURL: git@github.com:traPtitech/manifest.git
        path: preview-traq-template
        targetRevision: main
        helm:
          parameters:
            - name: number
              value: "{{number}}"
            - name: headSha
              value: "{{head_sha}}"
      project: preview
      destination:
        server: https://kubernetes.default.svc
        namespace: preview-traq
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
