apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://charts.longhorn.io
    name: longhorn
    version: 1.11.0
    includeCRDs: true
    namespace: longhorn-system
    releaseName: longhorn
    valuesFile: values.yaml

resources:
  - certificate.yaml
  - ingress-route.yaml
