global:
  timezone: Asia/Tokyo

# nodeSelector設定
longhornManager:
  nodeSelector: {}
longhornDriver:
  nodeSelector:
    kubernetes.io/hostname: csc301.tokyotech.org
longhornUI:
  nodeSelector:
    kubernetes.io/hostname: csc301.tokyotech.org

persistence:
  defaultClass: false # 性能をどの程度要求するか不明なため、一旦デフォルトにしない

preUpgradeChecker:
  jobEnabled: false # ArgoCDで管理する場合はfalse
