apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-controller

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ns-controller
  template:
    metadata:
      labels:
        app: ns-controller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
    spec:
      enableServiceLinks: false
      serviceAccountName: ns-controller

      volumes:
        - name: config
          configMap:
            name: ns-config
        - name: keys
          secret:
            secretName: ns-keys
        - name: known-hosts
          configMap:
            name: known-hosts

      containers:
        - name: ns-controller
          image: ns-controller
          imagePullPolicy: Always
          args:
            - --loglevel=debug
            - --config=/opt/config/ns.yaml
          ports:
            - containerPort: 2201
              name: ssh
            - containerPort: 8080
              name: webhook
            - containerPort: 10000
              name: grpc
            - containerPort: 9100
              name: metrics
          env:
            - name: NS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ns
                  key: db-password
            - name: NS_STORAGE_S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: ns
                  key: s3-access-key
            - name: NS_STORAGE_S3_ACCESSSECRET
              valueFrom:
                secretKeyRef:
                  name: ns
                  key: s3-access-secret
            - name: NS_IMAGE_REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ns
                  key: registry-password
            - name: NS_COMPONENTS_CONTROLLER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ns
                  key: controller-token
          volumeMounts:
            - mountPath: /opt/config/ns.yaml
              name: config
              subPath: ns.yaml
            - mountPath: /keys
              name: keys
            - mountPath: /root/.ssh/known_hosts
              name: known-hosts
              subPath: known_hosts
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "2"
              memory: "150Mi"
