apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jomon
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jomon.trap.jp`)
      kind: Rule
      services:
        - name: jomon-backend
          port: 80
        - name: jomon-frontend
          port: 80
  tls:
    secretName: jomon-tls
