namespace: monitor

helmCharts:
  - repo: https://grafana.github.io/helm-charts
    name: pyroscope
    version: "1.18.0"
    includeCRDs: true
    namespace: monitor
    releaseName: pyroscope
    valuesFile: values.yaml
