apiVersion: apps/v1
kind: Deployment
metadata:
  name: anke-to
  labels:
    app: anke-to

spec:
  replicas: 1
  selector:
    matchLabels:
      app: anke-to
  template:
    metadata:
      labels:
        app: anke-to
    spec:
      nodeSelector:
        kubernetes.io/hostname: las211.tokyotech.org
      containers:
        - name: anke-to
          image: ghcr.io/traptitech/anke-to:latest@sha256:699a6d29a29e2e384db3605b850e27c6588864d898219b51faef06ef9bb4be2f
          env:
            - name: MARIADB_USERNAME
              value: "service_anke_to"
            - name: MARIADB_HOSTNAME
              value: "tailscale.kmbk.tokyotech.org"
            - name: MARIADB_DATABASE
              value: "service_anke_to"
            - name: MARIADB_PORT
              value: "3306"
            - name: PORT
              value: ":1323"
            - name: TZ
              value: "Asia/Tokyo"
          envFrom:
            - secretRef:
                name: anke-to
          ports:
            - containerPort: 1323
