apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: knoq
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`knoq.trap.jp`) && PathPrefix(`/api`)
      kind: Rule
      middlewares:
        - name: auth-trap-jp-hard
          namespace: auth
      services:
        - name: knoq-backend
          port: 3000
    - match: Host(`knoq.trap.jp`)
      kind: Rule
      middlewares:
        - name: auth-trap-jp-hard
          namespace: auth
      services:
        - name: knoq-frontend
          port: 80
  tls:
    secretName: knoq-tls
