apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traq-widget

spec:
  entryPoints:
    - websecure
  tls:
    secretName: traq-tls
  routes:
    - kind: Rule
      match: Host(`q.trap.jp`) && PathPrefix(`/widget`)
      middlewares:
        - name: auth-trapti-tech-soft
          namespace: auth
        - name: strip-widget-prefix
          namespace: traq-server
      services:
        - namespace: traq-server
          kind: Service
          name: traq-widget
          port: 8003
          scheme: http
          weight: 1
