namespace: monitor

resources:
  - backup
  - blackbox-exporter
  - domain-exporter
  - grafana
  - grafana-mcp
  - kube-state-metrics
  - loki
  - node-exporter
  - s3-exporter
  - ssl-exporter
  - victoria-metrics
