apiVersion: apps/v1
kind: Deployment
metadata:
  name: knoq-frontend
spec:
  template:
    spec:
      containers:
        - name: knoq-frontend
          image: ghcr.io/traptitech/knoq-ui-v1:master@sha256:1bdc0f4e4f9d506e4d2286d6646d29fe7be33344f40d34a20df3676ade31d22d
