apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: registry

spec:
  entryPoints:
    - websecure
  tls:
    secretName: registry-tls
  routes:
    - kind: Rule
      match: Host(`registry.ns.trap.jp`)
      services:
        - namespace: harbor
          kind: Service
          name: harbor
          port: http
          scheme: http
          weight: 1
