resources:
- conoha-exporter
- grafana
- loki
- node-exporter
- s3-exporter
- victoria-metrics

images:
- name: grafana
  newName: grafana/grafana
  newTag: 10.0.1
- name: loki
  newName: grafana/loki
  newTag: 2.8.2
- name: node-exporter
  newName: quay.io/prometheus/node-exporter
  newTag: v1.6.0
- name: conoha-exporter
  newName: ghcr.io/traptitech/conoha_exporter
  newTag: 1.3.7
- name: s3-exporter
  newName: ghcr.io/traptitech/s3_exporter
  newTag: 0.5.2
- name: victoria-metrics
  newName: victoriametrics/victoria-metrics
  newTag: v1.91.3
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
