resources:
- grafana
- loki
- node-exporter
- prometheus
- s3-exporter

images:
- name: grafana
  newName: grafana/grafana
  newTag: 9.5.2
- name: loki
  newName: grafana/loki
  newTag: 2.8.0
- name: node-exporter
  newName: quay.io/prometheus/node-exporter
  newTag: v1.5.0
- name: s3-exporter
  newName: ghcr.io/traptitech/s3_exporter
  newTag: 0.5.2
- name: victoria-metrics
  newName: victoriametrics/victoria-metrics
  newTag: v1.91.2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
