resources:
  - backup
  - blackbox-exporter
  - conoha-exporter
  - domain-exporter
  - grafana
  - kube-state-metrics
  - loki
  - node-exporter
  - pyroscope
  - s3-exporter
  - ssl-exporter
  - victoria-metrics
