mode: dev-and-prod

repo:
  owner: traPtitech
  repo: rucQ-UI

webhook:
  name: rucq-ui-preview

tls:
  secretName: preview-rucq-ui-tls

host:
  base: rucq-ui-preview.trapti.tech

preview:
  imagePattern: "ghcr.io/traptitech/rucq-ui:preview-{{number}}-{{head_sha}}"

backend:
  matcher: PathPrefix(`/api/`)
  service:
    kind: Service
    namespace: 'rucq{{ if eq . "dev" }}-dev{{ end }}'
    name: rucq-backend-service
    port: 8080
    scheme: http

staging:
  enabled: true
  # renovate:image-full
  image: "ghcr.io/traptitech/rucq-ui:main@sha256:da59a29280754c901132f677d379bc3f5ff97c4f23958834376414b946ae4d27"

otherParameters:
  port: 80
