mode: dev-and-prod

repo:
  owner: traPtitech
  repo: rucQ-UI

webhook:
  name: rucq-ui-preview

tls:
  secretName: preview-rucq-ui-tls

host:
  base: rucq-ui-preview.trapti.tech

preview:
  imagePattern: "ghcr.io/traptitech/rucq-ui:preview-{{number}}-{{head_sha}}"

backend:
  matcher: PathPrefix(`/api/`)
  service:
    kind: Service
    namespace: 'rucq{{ if eq . "dev" }}-dev{{ end }}'
    name: rucq-backend-service
    port: 8080
    scheme: http

staging:
  enabled: true
  # renovate:image-full
  image: "ghcr.io/traptitech/rucq-ui:main@sha256:68145a1f3fe39e61a6e28b8130f6dcd043f35c492f4447bb6753b1c6f3fda072"

otherParameters:
  port: 80
