kind: Deployment
apiVersion: apps/v1
metadata:
  name: system-bot

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: system-bot
  template:
    metadata:
      labels:
        app: system-bot
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
        - name: system-bot
          image: ghcr.io/traptitech/traq-system-bot:1.1.0
          env:
            - name: BOT_SYSTEM_MESSAGE_CHANNEL_ID
              value: 9557ccd3-50b4-483c-a553-7003027203b8
            - name: TRAQ_ORIGIN
              value: wss://q.trap.jp
            - name: BOT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: system-bot
                  key: access-token

        - name: system-bot-accounts
          image: ghcr.io/traptitech/traq-system-bot:1.1.0
          env:
            - name: BOT_SYSTEM_MESSAGE_CHANNEL_ID
              value: 0ee22553-a95d-4f83-8863-ce5d6e0da5c3
            - name: BOT_SYSTEM_SUBSCRIBING_EVENTS
              value: USER_CREATED,USER_ACTIVATED
            - name: TRAQ_ORIGIN
              value: wss://q.trap.jp
            - name: BOT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: system-bot
                  key: access-token
