apiVersion: apps/v1
kind: Deployment
metadata:
  name: trap-collection-frontend
  labels:
    app.kubernetes.io/name: trap-collection-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: trap-collection-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: trap-collection-frontend
    spec:
      containers:
        - name: trap-collection-frontend
          image: ghcr.io/traptitech/trap-collection-admin:0.2.12
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
