apiVersion: apps/v1
kind: Deployment
metadata:
  name: trap-collection-frontend
  labels:
    app.kubernetes.io/name: trap-collection-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: trap-collection-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: trap-collection-frontend
    spec:
      containers:
        - name: trap-collection-frontend
          image: ghcr.io/traptitech/trap-collection-admin:main@sha256:dc708822ee29d84639baf3a8da55e56116261aea1997119bd47fedc1188438c0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
