apiVersion: v1
kind: Service
metadata:
  labels:
    app: portfolio-frontend
  name: portfolio-frontend
spec:
  ports:
    - name: http
      port: 3016
      targetPort: http
  selector:
    app: portfolio-frontend
