apiVersion: v1
kind: Service
metadata:
  labels:
    app: portfolio-backend
  name: portfolio-backend
spec:
  ports:
    - name: http
      port: 3009
      targetPort: http
  selector:
    app: portfolio-backend
